#!/usr/bin/env python3
"""Turn data/chat_filter_words.txt into src/chat/rnet_chat_filter_words.inc,
a C string literal the filter parses at first use. Run after editing the
list; commit both. The server includes the .txt directly (include_str!)."""
import pathlib, sys
root = pathlib.Path(__file__).resolve().parent.parent
src = root / 'data' / 'chat_filter_words.txt'
dst = root / 'src' / 'chat' / 'rnet_chat_filter_words.inc'
lines = []
for raw in src.read_text(encoding='utf-8').splitlines():
    line = raw.strip()
    if not line or line.startswith('#'):
        continue
    esc = line.encode('utf-8')
    body = ''.join('\\%03o' % b if b >= 0x80 or b in b'"\\' else chr(b) for b in esc)
    lines.append('"%s\\n"' % body)
dst.write_text('/* Generated by tools/gen_chat_filter_words.py from data/chat_filter_words.txt.\n'
               ' * Do not edit: edit the list and regenerate. */\n' + '\n'.join(lines) + '\n',
               encoding='utf-8')
print(f'{len(lines)} entries -> {dst.relative_to(root)}')
