# api_link_test: every function a public header declares must link.
#
# The frame-atomic WebSocket buffer (snesrecomp#104) deleted
# rnet_ws_read_text from rnet_ws.c but left it declared in rnet_ws.h. Nothing
# inside recomp-net called it, so every build and test stayed green; the first
# engine to call it would have found out at link time. This test is that
# engine: it takes the address of every rnet_* function named in
# include/recomp_net/*.h and links against recomp_net.
#
# The names come from a scan of the headers (comments and preprocessor lines
# removed, then every `rnet_<name>(`). The scan cannot invent a function: the
# generated file includes the real headers, so a name that is not a declared
# function fails to compile, and a declared one with no definition fails to
# link.

function(rnet_add_api_link_test)
  set(_inc "${CMAKE_CURRENT_SOURCE_DIR}/include")
  file(GLOB _headers CONFIGURE_DEPENDS "${_inc}/recomp_net/*.h")
  list(SORT _headers)
  # The glob tracks which headers exist; this re-runs the scan when one changes.
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${_headers})

  set(_includes "")
  set(_names "")
  foreach(_h IN LISTS _headers)
    get_filename_component(_base "${_h}" NAME)
    string(APPEND _includes "#include \"recomp_net/${_base}\"\n")
    file(READ "${_h}" _t)

    # Block comments (CMake regex has no lazy match: cut them one at a time).
    while(TRUE)
      string(FIND "${_t}" "/*" _open)
      if(_open EQUAL -1)
        break()
      endif()
      string(SUBSTRING "${_t}" 0 ${_open} _head)
      string(SUBSTRING "${_t}" ${_open} -1 _rest)
      string(FIND "${_rest}" "*/" _close)
      if(_close EQUAL -1)
        message(FATAL_ERROR "api_link_test: unterminated comment in ${_h}")
      endif()
      math(EXPR _close "${_close} + 2")
      string(SUBSTRING "${_rest}" ${_close} -1 _tail)
      set(_t "${_head} ${_tail}")
    endwhile()
    string(REGEX REPLACE "//[^\n]*" "" _t "${_t}")
    string(REGEX REPLACE "(^|\n)[ \t]*#[^\n]*" "\\1" _t "${_t}")

    # [A-Za-z0-9_]* in front stands in for a word boundary: a match that
    # does not start with rnet_ is part of a longer identifier. A `(` followed
    # by `*` is a function-pointer declarator (`rnet_u64 (*now_ms)(void *)`),
    # whose rnet_ word is the return type, not a function.
    string(REGEX MATCHALL
           "[A-Za-z0-9_]*rnet_[A-Za-z0-9_]+[ \t\r\n]*\\([ \t\r\n]*[^* \t\r\n]"
           _hits "${_t}")
    foreach(_hit IN LISTS _hits)
      string(REGEX REPLACE "[ \t\r\n]*\\(.*$" "" _name "${_hit}")
      if(_name MATCHES "^rnet_")
        list(APPEND _names "${_name}")
      endif()
    endforeach()
  endforeach()
  list(REMOVE_DUPLICATES _names)
  list(SORT _names)
  list(LENGTH _names _count)
  if(_count EQUAL 0)
    message(FATAL_ERROR "api_link_test: found no public functions under ${_inc}")
  endif()

  set(_table "")
  set(_labels "")
  foreach(_name IN LISTS _names)
    string(APPEND _table "    (rnet_api_fn)${_name},\n")
    string(APPEND _labels "    \"${_name}\",\n")
  endforeach()

  set(_src
"/* Generated by cmake/RnetApiLinkTest.cmake from the headers in
 * include/recomp_net. Do not edit: re-run CMake. */
${_includes}
#include <stdio.h>

typedef void (*rnet_api_fn)(void);

static const rnet_api_fn k_api[] = {
${_table}};

static const char *const k_names[] = {
${_labels}};

int main(void)
{
    unsigned long i, n = (unsigned long)(sizeof(k_api) / sizeof(k_api[0]));
    for (i = 0; i < n; ++i) {
        if (!k_api[i]) {
            fprintf(stderr, \"api_link_test: %s resolved to NULL\\n\", k_names[i]);
            return 1;
        }
    }
    printf(\"api_link_test: all %lu public functions link\\n\", n);
    return 0;
}
")
  set(_out "${CMAKE_CURRENT_BINARY_DIR}/rnet_api_link_test.c")
  # Rewrite only on change, so a re-configure does not rebuild the test.
  file(WRITE "${_out}.tmp" "${_src}")
  configure_file("${_out}.tmp" "${_out}" COPYONLY)

  add_executable(api_link_test "${_out}")
  target_link_libraries(api_link_test PRIVATE recomp_net)
  add_test(NAME api_link_test COMMAND api_link_test)
endfunction()
